/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCalculatorsRouteImport } from './routes/_authenticated/calculators'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations.new'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorsRoute =
  AuthenticatedCalculatorsRouteImport.update({
    id: '/calculators',
    path: '/calculators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calculators': typeof AuthenticatedCalculatorsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calculators': typeof AuthenticatedCalculatorsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/calculators'
    | '/customers'
    | '/dashboard'
    | '/follow-ups'
    | '/jobs'
    | '/reports'
    | '/leads/$id'
    | '/quotations/new'
    | '/leads/'
    | '/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/calculators'
    | '/customers'
    | '/dashboard'
    | '/follow-ups'
    | '/jobs'
    | '/reports'
    | '/leads/$id'
    | '/quotations/new'
    | '/leads'
    | '/quotations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/calculators'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/follow-ups'
    | '/_authenticated/jobs'
    | '/_authenticated/reports'
    | '/_authenticated/leads/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/leads/'
    | '/_authenticated/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculators': {
      id: '/_authenticated/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AuthenticatedCalculatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalculatorsRoute: typeof AuthenticatedCalculatorsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalculatorsRoute: AuthenticatedCalculatorsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
